language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    # XXX can't test these without a `msp430-elf-`  toolchain
    # - env: TARGET=msp430-none-elf
    #   rust: nightly

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
